### PR TITLE
Health Data - Rendering 

### PR DESCRIPTION
**Pull request by hodesza**
Referring to issue https://github.com/oslabs-beta/Chronos/issues/15
Please review this @mattljiang @DerekQuoc @kitloong1 
# Types of changes
- [ ]  Bugfix (change which fixes an issue)
- [ ]  New feature (change which adds functionality)
- [x]  Refactor (change which changes the codebase without affecting its external behavior)
- [ ]  Non-breaking change (fix or feature that would causes existing functionality to work as expected)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
# Purpose
- Fix the health data request query to NoSql databases. 
# Approach
- Update query to return at least 50 documents instead of 10 documents from Mongodb Atlas.

# Screenshot(s)
Screen Shot 2021-02-03 at 4 14 15 PM

### CODE REVIEW

**Review by kitloong1 — APPROVED** [review]
The health chart looks great!

**Comment by DerekQuoc** [comment]
@Vince the images above show 11:01AM, and 2:01PM, however on my computer the chart seems to work perfectly.

**Comment by hodesza** [comment]
@DerekQuoc 

Updated screenshot of Health Data to better reflect the functionality of Speed Charts. 
Please review and approve request.

**Comment by DerekQuoc** [comment]
Photos look correct, functionality looks solid. Approved.

**Comment by mattljiang** [comment]
Great catch on the Mongo error. Ideally we show a user-customizable time range, but that may be a future feature. This looks good for now.

**Pull request merged**
